### ISSUE TITLE
Verify smartfact pages are not cached

### ISSUE THREAD

**Issue by dneise** [fact-project/smart_fact_crawler#2]
Thomas Bretz reported of problems related to cached smartfact pages, when he developed the smartfact.js code.

One can check, whether the pages are cached, if the timestamps of pages we download and parse do not update as often as they are updated on the server. We do not know how often they are updated on the server, but lets anyway see how often the timestamps update on the pages we download.

**Comment by MaxNoe** [comment]
http://stackoverflow.com/questions/20198274/how-do-i-clear-cache-with-python-requests

**Comment by dneise** [comment]
Right, but saying that something works as expected and showing that it works is a difference.

I had a look at `/home/factwww/smartfact/data/sun.data` as an example. It updated once every 15seconds.

Then repeatedly parsed it like this:
```
while True: 
    print(time.asctime(), smart_fact_crawler.sun()["Time_Stamp"])
    time.sleep(1)
```

----

The result looked like this
```
Mon May 23 13:20:50 2016 2016-05-23 11:20:43.030000
Mon May 23 13:20:51 2016 2016-05-23 11:20:43.030000
Mon May 23 13:20:52 2016 2016-05-23 11:20:43.030000
[...]
Mon May 23 13:20:57 2016 2016-05-23 11:20:43.030000
Mon May 23 13:20:58 2016 2016-05-23 11:20:58.114000
Mon May 23 13:20:59 2016 2016-05-23 11:20:58.114000
[...]
Mon May 23 13:21:11 2016 2016-05-23 11:20:58.114000
Mon May 23 13:21:12 2016 2016-05-23 11:20:58.114000
Mon May 23 13:21:15 2016 2016-05-23 11:21:13.186000
Mon May 23 13:21:16 2016 2016-05-23 11:21:13.186000
[...]
Mon May 23 13:21:27 2016 2016-05-23 11:21:13.186000
Mon May 23 13:21:28 2016 2016-05-23 11:21:13.186000
Mon May 23 13:21:29 2016 2016-05-23 11:21:28.259000
Mon May 23 13:21:30 2016 2016-05-23 11:21:28.259000
[...]
Mon May 23 13:21:42 2016 2016-05-23 11:21:28.259000
Mon May 23 13:21:44 2016 2016-05-23 11:21:43.336000

```


So there is nothing cached exactly as expected.
